apiVersion: v1
kind: Secret
metadata:
  name: eventhub-kafka-credentials
data:
  authMode: c2FzbF9wbGFpbnRleHQ=
  username: JENvbm5lY3Rpb25TdHJpbmc=
  password: <echo -n '[eventhub-conn-string]' | base64>
